In [3]:
import numpy
import pandas as pd

In [4]:
detail_path = './rmds_q3_competition/competition_data/Q3_competition_detail_dataset.xlsx'
review_path = './rmds_q3_competition/competition_data/Q3_competition_review_dataset.xlsx'

# 1. Framing
- improve restaurant performance
- topic (covid data/ covid density) 
    - 1.covid-19 map: viz covid-19 rate and restaurant locations on the map
    - 2.covid-19 density over time + revenue pred: would people prefer to eat outside (dine-in & pickup) more? Does the percentage of people who choose dine-in/pick-up change during the pandemic
    - 3.should restaurant choose to offer deliver or dine-in options for thei customers?
- data
    - covid data
    - covid density
    - yelp api (transaction)
- modules

# 2. EDA

# 3. Distribution

In [7]:
detail_df = pd.read_excel(detail_path)
detail_df.head(3).T

,0,1,2
id,nzgC5hhlnSq2DYbJbtH5MQ,i-2aG9_PQBEy7LrsRv0Ivg,DJoeogRsOW5s9MzgveHQ2A
name,Foxy's Landing & Restaurant,Mosman's Steakhouse,El Tamarindo
is_claimed,True,True,True
is_closed,False,False,False
phone,1.66195e+10,1.66195e+10,1.66172e+10
review_count,52,63,11
categories01,breakfast_brunch,bars,salvadoran
categories02,tradamerican,steak,NaN
categories03,NaN,NaN,NaN
rating,4,3.5,3.5
price,$$,$$,$
transactions,[],[],[]
zip_code,93536,93536,93534
city,Lancaster,Lancaster,Lancaster
address,"['4555 W Avenue G', 'Lancaster, CA 93536']","['46645 W 60th W', 'Lancaster, CA 93536']","['551 W Ave I', 'Ste E', 'Lancaster, CA 93534']"
restaurant_url,https://www.yelp.com/biz/foxys-landing-and-res...,https://www.yelp.com/biz/mosmans-steakhouse-la...,https://www.yelp.com/biz/el-tamarindo-lancaste...
image_url,https://s3-media1.fl.yelpcdn.com/bphoto/LooWtz...,https://s3-media3.fl.yelpcdn.com/bphoto/JJ3mkC...,https://s3-media1.fl.yelpcdn.com/bphoto/UMSkfH...
latitude,34.7388,34.7306,34.7075
longitude,-118.216,-118.238,-118.146
photos,['https://s3-media1.fl.yelpcdn.com/bphoto/LooW...,['https://s3-media3.fl.yelpcdn.com/bphoto/JJ3m...,['https://s3-media1.fl.yelpcdn.com/bphoto/UMSk...
cross_streets,NaN,NaN,NaN

In [12]:
detail_df.loc[detail_df.transactions != '[]', :].shape

(7818, 21)

In [9]:
detail_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10710 entries, 0 to 10709
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              10710 non-null  object
 1   name            10710 non-null  object
 2   is_claimed      10710 non-null  bool
 3   is_closed       10710 non-null  bool
 4   phone           9993 non-null   float64
 5   review_count    10710 non-null  int64
 6   categories01    10710 non-null  object
 7   categories02    7434 non-null   object
 8   categories03    4034 non-null   object
 9   rating          10710 non-null  float64
 10  price           8374 non-null   object
 11  transactions    10710 non-null  object
 12  zip_code        10703 non-null  float64
 13  city            10710 non-null  object
 14  address         10710 non-null  object
 15  restaurant_url  10710 non-null  object
 16  image_url       10350 non-null  object
 17  latitude        10710 non-null  float64
 18  longitude       10710 non-null  float64
 19  photos          10710 non-null  object
 20  cross_streets   0 non-null      float64
dtypes: bool(2), float64(6), int64(1), object(12)
memory usage: 1.6+ MB

In [21]:
review_df = pd.read_excel(review_path)
review_df.head(3).T

,0,1,2
id,cal0Wpupxj9c_AV7WzDXsw,cal0Wpupxj9c_AV7WzDXsw,cal0Wpupxj9c_AV7WzDXsw
review_id,AyueC5Vq_5lUKJFqSzXWWw,yaH4AmHUz9b3Ywv4VtvU5g,YiuFLFWsrP92_QWa-d2W2Q
review_text,Slightly turned off by the hostess. She wasn't...,Wish I would have known about no brunch at the...,I had an amazing experience at Granville.\n\nw...
review_rating,3,3,5
review_time_created,2021-07-13 15:01:59,2021-07-06 13:50:42,2021-08-09 21:06:24

In [22]:
review_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32238 entries, 0 to 32237
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   32232 non-null  object
 1   review_id            30753 non-null  object
 2   review_text          30753 non-null  object
 3   review_rating        30753 non-null  float64
 4   review_time_created  30753 non-null  object
dtypes: float64(1), object(4)
memory usage: 1.2+ MB